### PR TITLE
Added GCC High

### PR DESCRIPTION
**Pull request by kwgoad**

### CODE REVIEW

**Comment by rolandbanks** [comment]
@danielabbatt I had a look at this and it looks OK code-wise but you might want to look.

**Review by danielabbatt — APPROVED** [review]
Yup looks like a good start for this.

**Comment by danielabbatt** [comment]
I'll do a nuget release - Thanks for the update

**Comment by danielabbatt** [comment]
1.2.32 released - did a bit of code cleanup while I was at it.

**Pull request merged**
